#!/bin/sh

case "$1" in
    start)
        echo "Starting gpio-logger"
        /usr/bin/gpio-logger &
        echo $! > /var/run/gpio-logger.pid
        ;;
    stop)
        echo "Stopping gpio-logger"
        kill `cat /var/run/gpio-logger.pid`
        rm /var/run/gpio-logger.pid
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

